import type { MeshBuildResult, ExportOptions } from '../../types';
import { transformMesh } from './AxisTransform';

export function exportObj(mesh: MeshBuildResult, materialName: string = 'material'): string {
  const lines: string[] = [];

  lines.push('# Generated by wippa-build');
  lines.push(`mtllib ${materialName}.mtl`);
  lines.push('');

  const vertexCount = mesh.positions.length / 3;
  if (vertexCount === 0) {
    return lines.join('\n');
  }

  for (let i = 0; i < vertexCount; i++) {
    const x = mesh.positions[i * 3];
    const y = mesh.positions[i * 3 + 1];
    const z = mesh.positions[i * 3 + 2];
    lines.push(`v ${x} ${y} ${z}`);
  }

  lines.push('');

  const uvCount = mesh.uvs.length / 2;
  for (let i = 0; i < uvCount; i++) {
    const u = mesh.uvs[i * 2];
    const v = mesh.uvs[i * 2 + 1];
    lines.push(`vt ${u} ${v}`);
  }

  lines.push('');

  const normalCount = mesh.normals.length / 3;
  for (let i = 0; i < normalCount; i++) {
    const x = mesh.normals[i * 3];
    const y = mesh.normals[i * 3 + 1];
    const z = mesh.normals[i * 3 + 2];
    lines.push(`vn ${x} ${y} ${z}`);
  }

  lines.push('');
  lines.push(`usemtl ${materialName}`);

  const triangleCount = mesh.triangleCount;
  if (triangleCount === 0) {
    return lines.join('\n');
  }

  for (let i = 0; i < triangleCount; i++) {
    const i0 = mesh.indices[i * 3] + 1;
    const i1 = mesh.indices[i * 3 + 1] + 1;
    const i2 = mesh.indices[i * 3 + 2] + 1;
    lines.push(`f ${i0}/${i0}/${i0} ${i1}/${i1}/${i1} ${i2}/${i2}/${i2}`);
  }

  return lines.join('\n');
}

export function exportMtl(
  materialName: string = 'material',
  textures: { albedo?: boolean; normal?: boolean } = {},
): string {
  const lines: string[] = [];

  lines.push('# Generated by wippa-build');
  lines.push('');
  lines.push(`newmtl ${materialName}`);
  lines.push('Ka 0.2 0.2 0.2');
  lines.push('Kd 0.8 0.8 0.8');
  lines.push('Ks 1.0 1.0 1.0');
  lines.push('Ns 100.0');
  lines.push('d 1.0');
  lines.push('illum 2');
  if (textures.albedo) lines.push('map_Kd albedo.png');
  if (textures.normal) lines.push('map_Kn normal.png');

  return lines.join('\n');
}

export function exportObjWithMtl(
  mesh: MeshBuildResult,
  options: ExportOptions,
  textures: { albedo?: boolean; normal?: boolean } = {},
): { obj: string; mtl: string; mtlName: string } {
  const materialName = 'material';
  const transformed = transformMesh(mesh, options.axisConvention, options.scale);
  const obj = exportObj(transformed, materialName);
  const mtl = exportMtl(materialName, textures);

  return { obj, mtl, mtlName: `${materialName}.mtl` };
}
