import type { MeshBuildResult, ExportOptions } from '../../types';

function transformPosition(
  x: number,
  y: number,
  z: number,
  axisConvention: string,
  scale: number,
): [number, number, number] {
  let tx = x * scale;
  let ty = y * scale;
  let tz = z * scale;

  if (axisConvention === 'unity') {
    const tmp = ty;
    ty = tz;
    tz = -tmp;
  } else if (axisConvention === 'unreal') {
    tx *= 100;
    ty *= 100;
    tz *= 100;
    const tmp = ty;
    ty = tz;
    tz = -tmp;
  }

  return [tx, ty, tz];
}

function transformNormal(
  x: number,
  y: number,
  z: number,
  axisConvention: string,
): [number, number, number] {
  const nx = x;
  let ny = y;
  let nz = z;

  if (axisConvention === 'unity') {
    const tmp = ny;
    ny = nz;
    nz = -tmp;
  } else if (axisConvention === 'unreal') {
    const tmp = ny;
    ny = nz;
    nz = -tmp;
  }

  return [nx, ny, nz];
}

export function exportObj(mesh: MeshBuildResult, materialName: string = 'material'): string {
  const lines: string[] = [];

  lines.push('# Generated by wippa-build');
  lines.push(`mtllib ${materialName}.mtl`);
  lines.push('');

  const vertexCount = mesh.positions.length / 3;
  if (vertexCount === 0) {
    return lines.join('\n');
  }

  for (let i = 0; i < vertexCount; i++) {
    const x = mesh.positions[i * 3];
    const y = mesh.positions[i * 3 + 1];
    const z = mesh.positions[i * 3 + 2];
    lines.push(`v ${x} ${y} ${z}`);
  }

  lines.push('');

  const uvCount = mesh.uvs.length / 2;
  for (let i = 0; i < uvCount; i++) {
    const u = mesh.uvs[i * 2];
    const v = mesh.uvs[i * 2 + 1];
    lines.push(`vt ${u} ${v}`);
  }

  lines.push('');

  const normalCount = mesh.normals.length / 3;
  for (let i = 0; i < normalCount; i++) {
    const x = mesh.normals[i * 3];
    const y = mesh.normals[i * 3 + 1];
    const z = mesh.normals[i * 3 + 2];
    lines.push(`vn ${x} ${y} ${z}`);
  }

  lines.push('');
  lines.push(`usemtl ${materialName}`);

  const triangleCount = mesh.triangleCount;
  if (triangleCount === 0) {
    return lines.join('\n');
  }

  for (let i = 0; i < triangleCount; i++) {
    const i0 = mesh.indices[i * 3] + 1;
    const i1 = mesh.indices[i * 3 + 1] + 1;
    const i2 = mesh.indices[i * 3 + 2] + 1;
    lines.push(`f ${i0}/${i0}/${i0} ${i1}/${i1}/${i1} ${i2}/${i2}/${i2}`);
  }

  return lines.join('\n');
}

export function exportMtl(materialName: string = 'material'): string {
  const lines: string[] = [];

  lines.push('# Generated by wippa-build');
  lines.push('');
  lines.push(`newmtl ${materialName}`);
  lines.push('Ka 0.2 0.2 0.2');
  lines.push('Kd 0.8 0.8 0.8');
  lines.push('Ks 1.0 1.0 1.0');
  lines.push('Ns 100.0');
  lines.push('d 1.0');
  lines.push('illum 2');
  lines.push('map_Kd albedo.png');

  return lines.join('\n');
}

export function exportObjWithMtl(
  mesh: MeshBuildResult,
  options: ExportOptions,
): { obj: string; mtl: string } {
  const materialName = 'material';
  const { axisConvention, scale } = options;

  const transformed: MeshBuildResult = {
    positions: new Float32Array(mesh.positions.length),
    normals: new Float32Array(mesh.normals.length),
    uvs: mesh.uvs,
    indices: mesh.indices,
    triangleCount: mesh.triangleCount,
    bounds: {
      min: [0, 0, 0],
      max: [0, 0, 0],
    },
  };

  const vertexCount = mesh.positions.length / 3;
  const minPos: [number, number, number] = [Infinity, Infinity, Infinity];
  const maxPos: [number, number, number] = [-Infinity, -Infinity, -Infinity];

  for (let i = 0; i < vertexCount; i++) {
    const px = mesh.positions[i * 3];
    const py = mesh.positions[i * 3 + 1];
    const pz = mesh.positions[i * 3 + 2];
    const [tx, ty, tz] = transformPosition(px, py, pz, axisConvention, scale);
    transformed.positions[i * 3] = tx;
    transformed.positions[i * 3 + 1] = ty;
    transformed.positions[i * 3 + 2] = tz;

    if (tx < minPos[0]) minPos[0] = tx;
    if (ty < minPos[1]) minPos[1] = ty;
    if (tz < minPos[2]) minPos[2] = tz;
    if (tx > maxPos[0]) maxPos[0] = tx;
    if (ty > maxPos[1]) maxPos[1] = ty;
    if (tz > maxPos[2]) maxPos[2] = tz;
  }

  for (let i = 0; i < vertexCount; i++) {
    const nx = mesh.normals[i * 3];
    const ny = mesh.normals[i * 3 + 1];
    const nz = mesh.normals[i * 3 + 2];
    const [tx, ty, tz] = transformNormal(nx, ny, nz, axisConvention);
    transformed.normals[i * 3] = tx;
    transformed.normals[i * 3 + 1] = ty;
    transformed.normals[i * 3 + 2] = tz;
  }

  transformed.bounds.min = minPos;
  transformed.bounds.max = maxPos;

  const obj = exportObj(transformed, materialName);
  const mtl = exportMtl(materialName);

  return { obj, mtl };
}
