import type { MeshBuildResult, ExportOptions } from '../../types';

const HEADER = 'Generated by wippa-build';

function transformPosition(
  x: number,
  y: number,
  z: number,
  axisConvention: string,
  scale: number,
): [number, number, number] {
  let tx = x * scale;
  let ty = y * scale;
  let tz = z * scale;

  if (axisConvention === 'unity') {
    const tmp = ty;
    ty = tz;
    tz = -tmp;
  } else if (axisConvention === 'unreal') {
    tx *= 100;
    ty *= 100;
    tz *= 100;
    const tmp = ty;
    ty = tz;
    tz = -tmp;
  }

  return [tx, ty, tz];
}

function transformNormal(
  x: number,
  y: number,
  z: number,
  axisConvention: string,
): [number, number, number] {
  const nx = x;
  let ny = y;
  let nz = z;

  if (axisConvention === 'unity' || axisConvention === 'unreal') {
    const tmp = ny;
    ny = nz;
    nz = -tmp;
  }

  return [nx, ny, nz];
}

function computeTriangleNormal(
  v0x: number, v0y: number, v0z: number,
  v1x: number, v1y: number, v1z: number,
  v2x: number, v2y: number, v2z: number,
): [number, number, number] {
  const e1x = v1x - v0x;
  const e1y = v1y - v0y;
  const e1z = v1z - v0z;
  const e2x = v2x - v0x;
  const e2y = v2y - v0y;
  const e2z = v2z - v0z;

  let nx = e1y * e2z - e1z * e2y;
  let ny = e1z * e2x - e1x * e2z;
  let nz = e1x * e2y - e1y * e2x;

  const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
  if (len > 0) {
    nx /= len;
    ny /= len;
    nz /= len;
  }

  return [nx, ny, nz];
}

export function exportStl(mesh: MeshBuildResult, options?: ExportOptions): Blob {
  if (mesh.triangleCount === 0) {
    return new Blob([], { type: 'application/octet-stream' });
  }

  const useTransform = options && options.axisConvention !== 'gltf';
  const axisConvention = options?.axisConvention ?? 'gltf';
  const scale = options?.scale ?? 1;

  const triangleCount = mesh.triangleCount;
  const bufferSize = 80 + 4 + triangleCount * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);
  const bytes = new Uint8Array(buffer);

  for (let i = 0; i < 80; i++) {
    bytes[i] = 0;
  }
  const headerBytes = new TextEncoder().encode(HEADER);
  for (let i = 0; i < Math.min(headerBytes.length, 79); i++) {
    bytes[i] = headerBytes[i];
  }

  view.setUint32(80, triangleCount, true);

  let offset = 84;

  for (let i = 0; i < triangleCount; i++) {
    const i0 = mesh.indices[i * 3];
    const i1 = mesh.indices[i * 3 + 1];
    const i2 = mesh.indices[i * 3 + 2];

    const v0x = mesh.positions[i0 * 3];
    const v0y = mesh.positions[i0 * 3 + 1];
    const v0z = mesh.positions[i0 * 3 + 2];
    const v1x = mesh.positions[i1 * 3];
    const v1y = mesh.positions[i1 * 3 + 1];
    const v1z = mesh.positions[i1 * 3 + 2];
    const v2x = mesh.positions[i2 * 3];
    const v2y = mesh.positions[i2 * 3 + 1];
    const v2z = mesh.positions[i2 * 3 + 2];

    const [fnx, fny, fnz] = computeTriangleNormal(v0x, v0y, v0z, v1x, v1y, v1z, v2x, v2y, v2z);

    let nv0x: number, nv0y: number, nv0z: number;
    let nv1x: number, nv1y: number, nv1z: number;
    let nv2x: number, nv2y: number, nv2z: number;
    let nnx: number, nny: number, nnz: number;

    if (useTransform) {
      [nv0x, nv0y, nv0z] = transformPosition(v0x, v0y, v0z, axisConvention, scale);
      [nv1x, nv1y, nv1z] = transformPosition(v1x, v1y, v1z, axisConvention, scale);
      [nv2x, nv2y, nv2z] = transformPosition(v2x, v2y, v2z, axisConvention, scale);
      [nnx, nny, nnz] = transformNormal(fnx, fny, fnz, axisConvention);
    } else {
      nv0x = v0x;
      nv0y = v0y;
      nv0z = v0z;
      nv1x = v1x;
      nv1y = v1y;
      nv1z = v1z;
      nv2x = v2x;
      nv2y = v2y;
      nv2z = v2z;
      nnx = fnx;
      nny = fny;
      nnz = fnz;
    }

    view.setFloat32(offset, nnx, true); offset += 4;
    view.setFloat32(offset, nny, true); offset += 4;
    view.setFloat32(offset, nnz, true); offset += 4;

    view.setFloat32(offset, nv0x, true); offset += 4;
    view.setFloat32(offset, nv0y, true); offset += 4;
    view.setFloat32(offset, nv0z, true); offset += 4;

    view.setFloat32(offset, nv1x, true); offset += 4;
    view.setFloat32(offset, nv1y, true); offset += 4;
    view.setFloat32(offset, nv1z, true); offset += 4;

    view.setFloat32(offset, nv2x, true); offset += 4;
    view.setFloat32(offset, nv2y, true); offset += 4;
    view.setFloat32(offset, nv2z, true); offset += 4;

    view.setUint16(offset, 0, true); offset += 2;
  }

  return new Blob([buffer], { type: 'application/octet-stream' });
}

export function exportStlString(mesh: MeshBuildResult): string {
  if (mesh.triangleCount === 0) {
    return '';
  }

  const lines: string[] = [];
  lines.push('solid wippa');

  const triangleCount = mesh.triangleCount;

  for (let i = 0; i < triangleCount; i++) {
    const i0 = mesh.indices[i * 3];
    const i1 = mesh.indices[i * 3 + 1];
    const i2 = mesh.indices[i * 3 + 2];

    const v0x = mesh.positions[i0 * 3];
    const v0y = mesh.positions[i0 * 3 + 1];
    const v0z = mesh.positions[i0 * 3 + 2];
    const v1x = mesh.positions[i1 * 3];
    const v1y = mesh.positions[i1 * 3 + 1];
    const v1z = mesh.positions[i1 * 3 + 2];
    const v2x = mesh.positions[i2 * 3];
    const v2y = mesh.positions[i2 * 3 + 1];
    const v2z = mesh.positions[i2 * 3 + 2];

    const [nx, ny, nz] = computeTriangleNormal(v0x, v0y, v0z, v1x, v1y, v1z, v2x, v2y, v2z);

    lines.push(`  facet normal ${nx} ${ny} ${nz}`);
    lines.push('    outer loop');
    lines.push(`      vertex ${v0x} ${v0y} ${v0z}`);
    lines.push(`      vertex ${v1x} ${v1y} ${v1z}`);
    lines.push(`      vertex ${v2x} ${v2y} ${v2z}`);
    lines.push('    endloop');
    lines.push('  endfacet');
  }

  lines.push('endsolid wippa');

  return lines.join('\n');
}
