import type { MeshBuildResult, ExportOptions } from '../../types';
import { transformMesh } from './AxisTransform';

const HEADER = 'Generated by wippa-build';

function computeTriangleNormal(
  v0x: number, v0y: number, v0z: number,
  v1x: number, v1y: number, v1z: number,
  v2x: number, v2y: number, v2z: number,
): [number, number, number] {
  const e1x = v1x - v0x;
  const e1y = v1y - v0y;
  const e1z = v1z - v0z;
  const e2x = v2x - v0x;
  const e2y = v2y - v0y;
  const e2z = v2z - v0z;

  let nx = e1y * e2z - e1z * e2y;
  let ny = e1z * e2x - e1x * e2z;
  let nz = e1x * e2y - e1y * e2x;

  const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
  if (len > 0) {
    nx /= len;
    ny /= len;
    nz /= len;
  }

  return [nx, ny, nz];
}

export function exportStl(mesh: MeshBuildResult, options?: ExportOptions): Blob {
  if (mesh.triangleCount === 0) {
    return new Blob([], { type: 'application/octet-stream' });
  }

  const exportMesh = options
    ? transformMesh(mesh, options.axisConvention, options.scale)
    : mesh;
  const triangleCount = exportMesh.triangleCount;
  const bufferSize = 80 + 4 + triangleCount * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);
  const bytes = new Uint8Array(buffer);

  for (let i = 0; i < 80; i++) bytes[i] = 0;
  const headerBytes = new TextEncoder().encode(HEADER);
  for (let i = 0; i < Math.min(headerBytes.length, 79); i++) bytes[i] = headerBytes[i];
  view.setUint32(80, triangleCount, true);

  let offset = 84;
  for (let i = 0; i < triangleCount; i++) {
    const i0 = exportMesh.indices[i * 3];
    const i1 = exportMesh.indices[i * 3 + 1];
    const i2 = exportMesh.indices[i * 3 + 2];
    const v0 = exportMesh.positions.slice(i0 * 3, i0 * 3 + 3);
    const v1 = exportMesh.positions.slice(i1 * 3, i1 * 3 + 3);
    const v2 = exportMesh.positions.slice(i2 * 3, i2 * 3 + 3);
    const [fnx, fny, fnz] = computeTriangleNormal(
      v0[0], v0[1], v0[2],
      v1[0], v1[1], v1[2],
      v2[0], v2[1], v2[2],
    );

    for (const value of [fnx, fny, fnz, ...v0, ...v1, ...v2]) {
      view.setFloat32(offset, value, true);
      offset += 4;
    }
    view.setUint16(offset, 0, true);
    offset += 2;
  }

  return new Blob([buffer], { type: 'application/octet-stream' });
}

export function exportStlString(mesh: MeshBuildResult): string {
  if (mesh.triangleCount === 0) {
    return '';
  }

  const lines: string[] = [];
  lines.push('solid wippa');

  const triangleCount = mesh.triangleCount;

  for (let i = 0; i < triangleCount; i++) {
    const i0 = mesh.indices[i * 3];
    const i1 = mesh.indices[i * 3 + 1];
    const i2 = mesh.indices[i * 3 + 2];

    const v0x = mesh.positions[i0 * 3];
    const v0y = mesh.positions[i0 * 3 + 1];
    const v0z = mesh.positions[i0 * 3 + 2];
    const v1x = mesh.positions[i1 * 3];
    const v1y = mesh.positions[i1 * 3 + 1];
    const v1z = mesh.positions[i1 * 3 + 2];
    const v2x = mesh.positions[i2 * 3];
    const v2y = mesh.positions[i2 * 3 + 1];
    const v2z = mesh.positions[i2 * 3 + 2];

    const [nx, ny, nz] = computeTriangleNormal(v0x, v0y, v0z, v1x, v1y, v1z, v2x, v2y, v2z);

    lines.push(`  facet normal ${nx} ${ny} ${nz}`);
    lines.push('    outer loop');
    lines.push(`      vertex ${v0x} ${v0y} ${v0z}`);
    lines.push(`      vertex ${v1x} ${v1y} ${v1z}`);
    lines.push(`      vertex ${v2x} ${v2y} ${v2z}`);
    lines.push('    endloop');
    lines.push('  endfacet');
  }

  lines.push('endsolid wippa');

  return lines.join('\n');
}
